# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[versions]
asciidoctorTabs = "1.0.0.beta.6"
asciidocPlugin = "4.0.4"
groovy = "4.0.26"
jetty = "10.0.24"
junit4 = "4.13.2"
junit5 = "5.12.0"
ratpack = "1.10.0-milestone-38"
sauceConnect = "1.153"
selenium = "4.27.0"
htmlUnitDriver = "4.13.0"
spock = "2.3-groovy-4.0"
threeTen = "1.8.0"
micronaut = "3.10.1" # Micronaut 3 is still supports Java 11

[libraries]
asciidoctorj = 'org.asciidoctor:asciidoctorj:2.5.13'
cglib = 'cglib:cglib:2.2'
codenarcGroovy4 = 'org.codenarc:CodeNarc:3.6.0-groovy-4.0'
codenarc = 'org.codenarc:CodeNarc:2.2.0'
commons-fileupload = 'commons-fileupload:commons-fileupload:1.5'
gebSpockGroovy25 = 'org.gebish:geb-spock:4.0'
grolifant = 'org.ysb33r.gradle:grolifant80:4.0.0'
groovy-bom = { module = 'org.apache.groovy:groovy-bom', version.ref = 'groovy' }
groovy25 = 'org.codehaus.groovy:groovy-all:2.5.23'
guava = 'com.google.guava:guava:33.4.0-jre'
htmlUnitDriver = { module = 'org.seleniumhq.selenium:htmlunit-driver', version.ref = 'htmlUnitDriver' }
jetty-server = { module = 'org.eclipse.jetty:jetty-server', version.ref = 'jetty' }
jetty-servlet = { module = 'org.eclipse.jetty:jetty-servlet', version.ref = 'jetty' }
jodd-core = 'org.jodd:jodd-core:5.3.0'
jodd-lagarto = 'org.jodd:jodd-lagarto:6.0.6'
jsoup = 'org.jsoup:jsoup:1.19.1'
junit-platform-launcher = 'org.junit.platform:junit-platform-launcher:1.12.0'
junit-platform-testkit = 'org.junit.platform:junit-platform-testkit:1.12.0'
junit4 = { module = 'junit:junit', version.ref = 'junit4' }
micronaut-bom = { module = 'io.micronaut:micronaut-bom', version.ref = 'micronaut' }
micronaut-inject-groovy = { module = 'io.micronaut:micronaut-inject-groovy' }
micronaut-runtime-groovy = { module = 'io.micronaut.groovy:micronaut-runtime-groovy' }
micronaut-http-client = { module = 'io.micronaut:micronaut-http-client' }
micronaut-http-server-netty = { module = 'io.micronaut:micronaut-http-server-netty' }
logback-classic = { module = "ch.qos.logback:logback-classic" }

junit5-jupiter-api = { module = 'org.junit.jupiter:junit-jupiter-api', version.ref = 'junit5' }
junit5-jupiter-engine = { module = 'org.junit.jupiter:junit-jupiter-engine', version.ref = 'junit5' }
junit5-jupiter-params = { module = 'org.junit.jupiter:junit-jupiter-params', version.ref = 'junit5' }
junit5-vintage-engine = { module = 'org.junit.vintage:junit-vintage-engine', version.ref = 'junit5' }
ratpack-test = {module = 'io.ratpack:ratpack-test', version.ref = 'ratpack' }
sauceConnect = { module = 'com.saucelabs:ci-sauce', version.ref = 'sauceConnect' }
selenium-api = { module = 'org.seleniumhq.selenium:selenium-api', version.ref = 'selenium' }
selenium-grid = { module = 'org.seleniumhq.selenium:selenium-grid', version.ref = 'selenium' }
selenium-support = { module = 'org.seleniumhq.selenium:selenium-support', version.ref = 'selenium' }
spock-core = { module = 'org.spockframework:spock-core', version.ref = 'spock' }
spockCoreGroovy25 = 'org.spockframework:spock-core:1.3-groovy-2.5'
spockCoreGroovy3 = 'org.spockframework:spock-core:2.3-groovy-3.0'
systemLambda = 'com.github.stefanbirkner:system-lambda:1.2.1'
testcontainers-selenium = 'org.testcontainers:selenium:1.20.4'
testng = 'org.testng:testng:7.5.1'
threeTen-extra = { module = 'org.threeten:threeten-extra', version.ref = 'threeTen' }

[plugins]
asciidoc = { id = 'org.asciidoctor.jvm.convert', version.ref = 'asciidocPlugin' }
asciidoc-gems = { id = 'org.asciidoctor.jvm.gems', version.ref = 'asciidocPlugin' }
asl2 = { id = 'com.energizedwork.asl2', version = '1.1' }
nexusPublish = { id = 'io.github.gradle-nexus.publish-plugin', version = '2.0.0' }
node = { id = 'com.github.node-gradle.node', version = '7.1.0' }
